### PR TITLE
Doc Week update: New Compute features

### PR DESCRIPTION
**Pull request by mlgordon**
@mekaufman

### CODE REVIEW

**Comment by mlgordon** [comment]
@mekaufman Thank you for pointing that out! I went ahead and updated those conrefs. Should be set to go now.

**Comment by mlgordon** [comment]
@mekaufman Also, the date you changed it to isn't technically accurate. Do we have to add a specific date?

**Comment by mekaufman** [comment]
@mlgordon Yes, the posts should have a date. If each was available at a separate time then you can separate them with the date they were available.

**Comment by mekaufman** [comment]
Maybe it's just VS features as title and the following features are available rather than making them sound "new" if they aren't. And, moving forward each can be posted when they actually become available.

**Comment by mlgordon** [comment]
Changed the header to "Virtual server features".

**Comment by mlgordon** [comment]
Thanks for fixing the external link icon. Won't that date confuse users? It sounds like these features are new as of today.

**Comment by mekaufman** [comment]
@mlgordon Changed now to currently, so we aren't publicizing hey look what's new but more of check out what we have

**Comment by mlgordon** [comment]
@mekaufman This is what I'm concerned about: **New as of: 16 Nov 2018**

**Comment by mekaufman** [comment]
@mlgordon What date would you like to backdate it to?

**Comment by mlgordon** [comment]
@mekaufman Some of the features are end of 3Q and beginning of 4Q. @stemke and @gudrun-wolfgram what do you think?

**Comment by mekaufman** [comment]
I suggest going with what we have: an entry for today that just calls out what is available for the service. Or, let's split them out and put a backdated date on each that makes general sense with timing.

**Comment by gudrun-wolfgram** [comment]
@mekaufman @mlgordon - Thanks for your work on the virtual servers what's new entry! 

I am good with the Nov 16 date. All of these features are within the last 6 weeks, so pretty recent.

**Comment by gudrun-wolfgram** [comment]
@mekaufman - Yesterday, I missed seeing the new virtual servers entry, but today I see it in the Compute section. I noticed that there are two identical entries... One right after the **Compute** heading and again after the **Latest updates for IBM Cloud Kubernetes Service**. 

We should probably remove one. If you like, I can make a pull request to delete one.

**Comment by mekaufman** [comment]
@gudrun-wolfgram Fixed!

**Comment by gudrun-wolfgram** [comment]
Thanks @mekaufman!

**Pull request merged**
